### PR TITLE
create Dockerfile and docker-compose file

### PR DESCRIPTION
**Pull request by aquiles23**
## Issue

Related to issue #29 

## Notes
- Dockerfile and docker-compose.yml create on top of the image `node:14.17.5`
- There is instructions on README.md on how to use the docker

### CODE REVIEW

**Comment by aquiles23** [comment]
i change the tag to version 16.7

**Comment by mansogf** [comment]
> i change the tag to version 16.7

Great!

**Comment by mansogf** [comment]
@aquiles23 , is this PR ready for review?

**Comment by aquiles23** [comment]
> @aquiles23 , is this PR ready for review?

yes

**Pull request closed without merging**
