### PR TITLE
Fix Footer

### PR DESCRIPTION
**Pull request by fellipe-araujo**
## Description

This Pull Request was realized:
* Fixed footer to always remain at the bottom of the page.

## Related Issue
#51

### CODE REVIEW

**Comment by fellipe-araujo** [comment]
I finished this issue. @mansogf

**Comment by fellipe-araujo** [comment]
I found some bugs in production mode, i will fix.

**Comment by fellipe-araujo** [comment]
Bugs fixed. The PR is ready to be revised.

**Comment by mansogf** [comment]
Awesome, @fellipe-araujo !

**Pull request merged**
